version: "3.3"
services:
  mailhog:
    container_name: gca-mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
  database:
    container_name: gca-database
    image: mongo:latest
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: gca
    ports:
      - 27017:27017
    volumes:
      - ./.database:/data/db
